
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

[enderio]
	#The default byproduct material to output in Ender IO's sagmill.
	byproduct = "minecraft:cobblestone"

[exnihilocreatio]
	#The default base to sieve in Ex Nihilo Creatio to get ore pieces.
	oreBase = "#gravel"
	#The output chance of the sieve recipes added using a flint mesh.
	sieveFlintChance = 0.05000000074505806
	#The output chance of the sieve recipes added using an iron mesh.
	sieveIronChance = 0.07500000298023224
	#The output chance of the sieve recipes added using a diamond mesh.
	sieveDiamondChance = 0.15000000596046448

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"

